apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: componenta-devfile-sample-go-basic-private-devfile-nested-kevp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: componenta-devfile-sample-go-basic-private-devfile-nested-kevp
    app.kubernetes.io/part-of: mc-golang-nested
  name: componenta-devfile-sample-go-basic-private-devfile-nested-kevp
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: componenta-devfile-sample-go-basic-private-devfile-nested-kevp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: componenta-devfile-sample-go-basic-private-devfile-nested-kevp
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-feat-tenant/mc-golang-nested/componenta-devfile-sample-go-basic-private-devfile-nested-kevp@sha256:cf18bf6b1a5538455fe21840f31d7b8bb89c384e66805570496839ee16df092e
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 12m
            memory: 18Mi
status: {}
